### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MoriZalev** [MfaXyz/Crypto-Triangular-Arbitrage-Bot#5]
![image](https://user-images.githubusercontent.com/106540747/180320908-3ae4eb32-da29-41ad-8655-9b2d57872866.png)

**Comment by MfaXyz** [comment]
Hello,
Please read documentation to understand how to get your account and use that on your code:
https://github.com/Kucoin/kucoin-python-sdk

**Comment by MoriZalev** [comment]
Hello, is it not possible to earn this, there are examples?

**Comment by MfaXyz** [comment]
Hello there,
No! 
Actually, Because there is not enough speed to order execution and catch opportunities :)
